import type { QuizExercise } from '../shared/quiz'
import type { Stage } from '../types'

/**
 * Modulo 0 — 1o ao 3o ano. Enunciados curtos, poucas alternativas (3 em vez de 4) e sempre
 * com apoio visual onde da: a crianca desta faixa le pouco, entao a pergunta precisa se
 * resolver olhando a figura.
 */
export const primeirosNumerosStages: Stage<QuizExercise>[] = [
  {
    id: 'etapa-1',
    title: 'Contar, ler e comparar numeros',
    curriculum: 'base do 1o ano — BNCC',
    years: [1],
    exercises: [
      {
        id: 'pn1-01',
        bloom: 'lembrar',
        prompt: 'Quantas bolinhas voce ve?',
        hint: 'Aponte para cada bolinha e conte em voz alta: um, dois, tres...',
        visual: { kind: 'contagem', count: 6 },
        options: ['6', '5', '7'],
        answerIndex: 0,
      },
      {
        id: 'pn1-02',
        bloom: 'lembrar',
        prompt: 'Quantas bolinhas voce ve?',
        hint: 'Conte de dez em dez: a primeira fileira cheia ja tem 10.',
        visual: { kind: 'contagem', count: 13 },
        options: ['13', '12', '30'],
        answerIndex: 0,
      },
      {
        id: 'pn1-03',
        bloom: 'entender',
        prompt: 'Qual numero vem depois do 7?',
        hint: 'Conte na reta: 5, 6, 7 e o proximo.',
        visual: { kind: 'reta', max: 10, marks: [7] },
        options: ['8', '6', '9'],
        answerIndex: 0,
      },
      {
        id: 'pn1-04',
        bloom: 'entender',
        prompt: 'Qual destes numeros e o maior?',
        hint: 'Na reta, quanto mais para a direita, maior o numero.',
        visual: { kind: 'reta', max: 10, marks: [4, 9] },
        options: ['9', '4', 'sao iguais'],
        answerIndex: 0,
      },
      {
        id: 'pn1-05',
        bloom: 'aplicar',
        prompt: 'Qual numero esta faltando: 5, 6, __, 8?',
        hint: 'Conte devagar a partir do 5 e veja qual pulou.',
        visual: { kind: 'reta', max: 10, marks: [5, 6, 8] },
        options: ['7', '9', '4'],
        answerIndex: 0,
      },
      {
        id: 'pn1-06',
        bloom: 'analisar',
        prompt: 'Sao mais bolinhas que 10 ou menos que 10?',
        hint: 'Uma fileira cheia tem 10. Sobrou alguma bolinha depois dela?',
        visual: { kind: 'contagem', count: 8 },
        options: ['Menos que 10', 'Mais que 10', 'Exatamente 10'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-2',
    title: 'Juntar, separar e o valor de cada casa',
    curriculum: 'base do 1o e 2o ano — BNCC',
    years: [1, 2],
    exercises: [
      {
        id: 'pn2-01',
        bloom: 'entender',
        prompt: 'Quantas dezenas e quantas unidades tem o numero 24?',
        hint: 'Dezena e um grupo de 10. Quantos grupos de 10 cabem em 24?',
        options: ['2 dezenas e 4 unidades', '4 dezenas e 2 unidades', '24 dezenas'],
        answerIndex: 0,
      },
      {
        id: 'pn2-02',
        bloom: 'entender',
        prompt: 'Qual numero tem 3 dezenas e 5 unidades?',
        hint: '3 grupos de 10 dao 30. Depois junte as 5 unidades.',
        options: ['35', '53', '305'],
        answerIndex: 0,
      },
      {
        id: 'pn2-03',
        bloom: 'aplicar',
        prompt: 'Quanto e 10 + 6?',
        hint: 'Comece do 10 e conte seis a mais.',
        visual: { kind: 'contagem', count: 16 },
        options: ['16', '61', '7'],
        answerIndex: 0,
      },
      {
        id: 'pn2-04',
        bloom: 'aplicar',
        prompt: 'O numero 20 tem quantas unidades sozinhas, fora das dezenas?',
        hint: 'O zero mostra que nao sobrou nenhuma unidade solta.',
        options: ['Nenhuma', 'Duas', 'Vinte'],
        answerIndex: 0,
      },
      {
        id: 'pn2-05',
        bloom: 'aplicar',
        prompt: 'Como o numero 18 pode ser separado?',
        hint: 'Pense em uma dezena e o que sobra.',
        options: ['10 + 8', '1 + 8', '18 + 0 dezenas'],
        answerIndex: 0,
      },
      {
        id: 'pn2-06',
        bloom: 'analisar',
        prompt: 'Trocando a ordem dos algarismos de 47, que numero aparece?',
        hint: 'O 4 vira unidade e o 7 vira dezena. Ficou maior ou menor?',
        options: ['74', '47', '11'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-3',
    title: 'Somar e subtrair',
    curriculum: 'base do 2o e 3o ano — BNCC',
    years: [2, 3],
    exercises: [
      {
        id: 'pn3-03',
        bloom: 'entender',
        prompt: 'Se 8 + 5 = 13, quanto e 13 - 5?',
        hint: 'Subtrair desfaz a soma: se juntou 5, tirar 5 volta ao numero de antes.',
        options: ['8', '5', '18'],
        answerIndex: 0,
      },
      {
        id: 'pn3-01',
        bloom: 'aplicar',
        prompt: 'Quanto e 7 + 5?',
        hint: 'Complete o 10 primeiro: 7 + 3 da 10, e ainda sobram 2.',
        visual: { kind: 'contagem', count: 12 },
        options: ['12', '11', '13'],
        answerIndex: 0,
      },
      {
        id: 'pn3-02',
        bloom: 'aplicar',
        prompt: 'Quanto e 14 - 6?',
        hint: 'Desca ate o 10 primeiro: 14 - 4 da 10, e ainda faltam tirar 2.',
        options: ['8', '7', '9'],
        answerIndex: 0,
      },
      {
        id: 'pn3-04',
        bloom: 'aplicar',
        prompt: 'Tinha 9 figurinhas e ganhei 7. Com quantas fiquei?',
        hint: 'Junte as duas quantidades: 9 + 7.',
        options: ['16', '15', '2'],
        answerIndex: 0,
      },
      {
        id: 'pn3-05',
        bloom: 'aplicar',
        prompt: 'Tinha 15 balas e dei 6 para um amigo. Quantas sobraram?',
        hint: 'Dar embora e tirar: 15 - 6.',
        options: ['9', '8', '21'],
        answerIndex: 0,
      },
      {
        id: 'pn3-06',
        bloom: 'analisar',
        prompt: 'Qual conta tem o mesmo resultado que 6 + 8?',
        hint: 'Trocar a ordem na soma nao muda o total.',
        options: ['8 + 6', '8 - 6', '6 + 6'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-4',
    title: 'Padroes, formas e primeiros graficos',
    curriculum: 'base do 3o ano — BNCC',
    years: [3],
    exercises: [
      {
        id: 'pn4-03',
        bloom: 'lembrar',
        prompt: 'Quantos lados tem um triangulo?',
        hint: 'O nome ja ajuda: "tri" quer dizer tres.',
        options: ['3', '4', '1'],
        answerIndex: 0,
      },
      {
        id: 'pn4-01',
        bloom: 'entender',
        prompt: 'Qual numero continua o padrao: 2, 4, 6, 8, __?',
        hint: 'Cada numero pula dois para frente.',
        visual: { kind: 'reta', max: 10, marks: [2, 4, 6, 8] },
        options: ['10', '9', '12'],
        answerIndex: 0,
      },
      {
        id: 'pn4-02',
        bloom: 'entender',
        prompt: 'Qual numero continua o padrao: 5, 10, 15, __?',
        hint: 'Sao os numeros da tabuada do 5, de cinco em cinco.',
        options: ['20', '16', '25'],
        answerIndex: 0,
      },
      {
        id: 'pn4-04',
        bloom: 'entender',
        prompt: 'Uma figura com 4 lados iguais e 4 cantos iguais e um...',
        hint: 'Pense na forma de um azulejo ou de um dado visto de frente.',
        visual: { kind: 'grade-area', rows: 3, cols: 3 },
        options: ['Quadrado', 'Triangulo', 'Circulo'],
        answerIndex: 0,
      },
      {
        id: 'pn4-05',
        bloom: 'aplicar',
        prompt: 'Nesta figura de 3 por 4, quantos quadradinhos ha ao todo?',
        hint: 'Conte uma fileira e repita para as outras.',
        visual: { kind: 'grade-area', rows: 3, cols: 4 },
        options: ['12', '7', '9'],
        answerIndex: 0,
      },
      {
        id: 'pn4-06',
        bloom: 'analisar',
        prompt: 'Uma tabela mostra: segunda 3 estrelas, terca 5 estrelas, quarta 2 estrelas. Em que dia foram mais estrelas?',
        hint: 'Compare os tres numeros e escolha o maior.',
        options: ['Terca', 'Segunda', 'Quarta'],
        answerIndex: 0,
      },
    ],
  },
]
