import type { QuizExercise } from '../shared/quiz'
import type { Stage } from '../types'

/**
 * Modulo 2 — 5o ao 8o ano. Apoia-se na ponte fracao/porcentagem que a etapa 2 de Fracoes
 * ja abre, e usa a grade de cem quadrados como representacao canonica: por cento e,
 * literalmente, "de cada cem".
 */
export const porcentagemStages: Stage<QuizExercise>[] = [
  {
    id: 'etapa-1',
    title: 'Porcentagens simples e a ponte com fracoes',
    curriculum: 'base do 5o e 6o ano — BNCC',
    years: [5, 6],
    exercises: [
      {
        id: 'pc1-01',
        bloom: 'lembrar',
        prompt: 'Quantos por cento da grade estao pintados?',
        hint: 'A grade tem 100 quadradinhos. Conte quantas fileiras de 10 estao pintadas.',
        visual: { kind: 'centena', filled: 50 },
        options: ['50%', '5%', '500%', '25%'],
        answerIndex: 0,
      },
      {
        id: 'pc1-02',
        bloom: 'entender',
        prompt: 'Que fracao corresponde a 50% da grade?',
        hint: 'Metade da grade pintada e metade do inteiro.',
        visual: { kind: 'centena', filled: 50 },
        options: ['1/2', '1/4', '5/10 de 10', '1/50'],
        answerIndex: 0,
      },
      {
        id: 'pc1-03',
        bloom: 'entender',
        prompt: 'A quarta parte de um todo corresponde a quantos por cento?',
        hint: 'Divida os 100 quadradinhos em 4 partes iguais.',
        visual: { kind: 'centena', filled: 25 },
        options: ['25%', '4%', '40%', '75%'],
        answerIndex: 0,
      },
      {
        id: 'pc1-04',
        bloom: 'entender',
        prompt: 'Quantos por cento da barra estao pintados?',
        hint: '3 partes pintadas de 4 partes iguais. Cada parte vale 25%.',
        visual: { kind: 'fracao', shape: 'bar', n: 3, d: 4 },
        options: ['75%', '34%', '25%', '43%'],
        answerIndex: 0,
      },
      {
        id: 'pc1-05',
        bloom: 'aplicar',
        prompt: 'A decima parte de um todo, 1/10, e quantos por cento?',
        hint: '100 dividido em 10 partes iguais da 10 em cada parte.',
        visual: { kind: 'centena', filled: 10 },
        options: ['10%', '1%', '110%', '20%'],
        answerIndex: 0,
      },
      {
        id: 'pc1-06',
        bloom: 'analisar',
        prompt: 'Se 100% e o todo, o que sobra depois de tirar 30%?',
        hint: 'O todo sempre soma 100%. Quanto falta para completar?',
        visual: { kind: 'centena', filled: 70 },
        options: ['70%', '30%', '100%', '60%'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-2',
    title: 'Porcentagem de uma quantidade',
    curriculum: 'base do 6o e 7o ano — BNCC',
    years: [6, 7],
    exercises: [
      {
        id: 'pc2-01',
        bloom: 'aplicar',
        prompt: 'Quanto e 50% de 40 figurinhas?',
        hint: '50% e a metade. Metade de 40.',
        visual: { kind: 'centena', filled: 50 },
        options: ['20', '50', '10', '80'],
        answerIndex: 0,
      },
      {
        id: 'pc2-02',
        bloom: 'aplicar',
        prompt: 'Quanto e 10% de 250 reais?',
        hint: 'Para achar 10%, divida por 10.',
        options: ['25 reais', '10 reais', '2,50 reais', '100 reais'],
        answerIndex: 0,
      },
      {
        id: 'pc2-03',
        bloom: 'aplicar',
        prompt: 'Quanto e 25% de 80 paginas?',
        hint: '25% e a quarta parte. Divida 80 por 4.',
        visual: { kind: 'centena', filled: 25 },
        options: ['20 paginas', '25 paginas', '40 paginas', '4 paginas'],
        answerIndex: 0,
      },
      {
        id: 'pc2-04',
        bloom: 'aplicar',
        prompt: 'Uma turma tem 30 alunos e 20% faltaram. Quantos faltaram?',
        hint: '10% de 30 e 3. E 20% e o dobro disso.',
        options: ['6 alunos', '20 alunos', '3 alunos', '10 alunos'],
        answerIndex: 0,
      },
      {
        id: 'pc2-05',
        bloom: 'analisar',
        prompt: 'Como calcular 15% de 200 usando calculo mental?',
        hint: 'Quebre em partes faceis: 10% mais a metade de 10%.',
        options: [
          '10% de 200 (20) mais 5% (10), total 30',
          'Dividir 200 por 15',
          'Multiplicar 200 por 15',
          '15 mais 200',
        ],
        answerIndex: 0,
      },
      {
        id: 'pc2-06',
        bloom: 'avaliar',
        prompt: 'O que da mais: 50% de 60 ou 25% de 100?',
        hint: 'Calcule os dois: metade de 60 da 30, e a quarta parte de 100 da 25.',
        options: ['50% de 60', '25% de 100', 'Os dois dao o mesmo', 'Nao da para comparar'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-3',
    title: 'Acrescimos e descontos (educacao financeira)',
    curriculum: 'base do 7o e 8o ano — BNCC',
    years: [7, 8],
    exercises: [
      {
        id: 'pc3-01',
        bloom: 'aplicar',
        prompt: 'Uma camiseta de 80 reais esta com 10% de desconto. Quanto voce paga?',
        hint: '10% de 80 e 8. Tire esse desconto do preco.',
        options: ['72 reais', '8 reais', '70 reais', '88 reais'],
        answerIndex: 0,
      },
      {
        id: 'pc3-02',
        bloom: 'aplicar',
        prompt: 'Um jogo de 200 reais aumentou 25%. Qual o novo preco?',
        hint: '25% de 200 e 50. Some ao preco antigo.',
        options: ['250 reais', '225 reais', '150 reais', '205 reais'],
        answerIndex: 0,
      },
      {
        id: 'pc3-03',
        bloom: 'analisar',
        prompt: 'Pagar 70 reais numa mochila que custava 100 significa qual desconto?',
        hint: 'Quanto foi abatido? E esse valor, em cada 100, e quantos por cento?',
        visual: { kind: 'centena', filled: 70 },
        options: ['30%', '70%', '20%', '10%'],
        answerIndex: 0,
      },
      {
        id: 'pc3-04',
        bloom: 'analisar',
        prompt: 'Qual desconto e melhor num produto de 100 reais: 20% ou 25 reais?',
        hint: '20% de 100 e 20 reais. Compare com os 25 reais.',
        options: ['25 reais de desconto', '20% de desconto', 'Sao iguais', 'Depende da loja'],
        answerIndex: 0,
      },
      {
        id: 'pc3-05',
        bloom: 'avaliar',
        prompt: 'Um preco de 100 reais sobe 10% e depois cai 10%. Volta a 100?',
        hint: 'Sobe para 110; os 10% de queda sao calculados sobre 110, nao sobre 100.',
        options: ['Nao, fica 99 reais', 'Sim, volta a 100 reais', 'Nao, fica 101 reais', 'Nao, fica 90 reais'],
        answerIndex: 0,
      },
      {
        id: 'pc3-06',
        bloom: 'avaliar',
        prompt: 'Guardar 20% de uma mesada de 50 reais, por 3 meses, junta quanto?',
        hint: '20% de 50 da 10 por mes. Multiplique pelos 3 meses.',
        options: ['30 reais', '10 reais', '20 reais', '60 reais'],
        answerIndex: 0,
      },
    ],
  },
]
