import type { QuizExercise } from '../shared/quiz'
import type { Stage } from '../types'

/**
 * Modulo 5 — Grandezas e Medidas ao longo do Fundamental. Perimetro usa o contorno da figura,
 * area usa grade de quadradinhos e volume usa bloco 3D: em cada caso a conta aparece depois
 * de a figura deixar o resultado obvio.
 */
export const grandezasStages: Stage<QuizExercise>[] = [
  {
    id: 'etapa-1',
    title: 'Comprimento, massa, capacidade e tempo',
    curriculum: 'base do 3o e 4o ano — BNCC',
    years: [3, 4],
    exercises: [
      {
        id: 'gm1-01',
        bloom: 'lembrar',
        prompt: 'Quantos centimetros tem 1 metro?',
        hint: 'Centi quer dizer centesima parte: sao cem pedacinhos em um metro.',
        options: ['100 cm', '10 cm', '1000 cm', '50 cm'],
        answerIndex: 0,
      },
      {
        id: 'gm1-03',
        bloom: 'lembrar',
        prompt: 'Quantos gramas tem 1 quilograma?',
        hint: 'Quilo quer dizer mil.',
        options: ['1000 g', '100 g', '10 g', '10000 g'],
        answerIndex: 0,
      },
      {
        id: 'gm1-02',
        bloom: 'entender',
        prompt: 'Quantos metros sao 350 centimetros?',
        hint: 'Cada 100 cm fecha 1 metro. Quantos cem cabem em 350?',
        options: ['3,5 m', '35 m', '0,35 m', '350 m'],
        answerIndex: 0,
      },
      {
        id: 'gm1-04',
        bloom: 'aplicar',
        prompt: 'Uma garrafa tem 1,5 litro. Quantos mililitros sao?',
        hint: '1 litro tem 1000 ml; meio litro tem 500 ml.',
        options: ['1500 ml', '150 ml', '15 ml', '15000 ml'],
        answerIndex: 0,
      },
      {
        id: 'gm1-05',
        bloom: 'aplicar',
        prompt: 'Um filme comeca as 14h30 e dura 1h45. A que horas termina?',
        hint: 'Some 1 hora (15h30) e depois os 45 minutos, passando da hora cheia.',
        options: ['16h15', '15h75', '16h45', '15h15'],
        answerIndex: 0,
      },
      {
        id: 'gm1-06',
        bloom: 'analisar',
        prompt: 'Qual e maior: 2500 g ou 2 kg?',
        hint: 'Coloque as duas na mesma unidade: 2 kg sao 2000 g.',
        options: ['2500 g', '2 kg', 'Sao iguais', 'Nao da para comparar'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-2',
    title: 'Perimetro de figuras planas',
    curriculum: 'base do 4o e 5o ano — BNCC',
    years: [4, 5],
    exercises: [
      {
        id: 'gm2-01',
        bloom: 'entender',
        prompt: 'O perimetro e a medida do que, numa figura?',
        hint: 'Imagine andar em volta da figura, pisando em cada lado.',
        options: ['Do contorno, somando os lados', 'Da parte de dentro', 'Da altura', 'Do maior lado'],
        answerIndex: 0,
      },
      {
        id: 'gm2-02',
        bloom: 'aplicar',
        prompt: 'Qual o perimetro deste retangulo de 6 por 4?',
        hint: 'Sao dois lados de 6 e dois de 4. Some os quatro.',
        visual: { kind: 'contorno', largura: 6, altura: 4 },
        options: ['20', '24', '10', '14'],
        answerIndex: 0,
      },
      {
        id: 'gm2-03',
        bloom: 'aplicar',
        prompt: 'Um quadrado tem lado 7. Qual o perimetro?',
        hint: 'No quadrado os quatro lados sao iguais: 7 quatro vezes.',
        options: ['28', '49', '14', '21'],
        answerIndex: 0,
      },
      {
        id: 'gm2-04',
        bloom: 'aplicar',
        prompt: 'Quantos metros de cerca para um terreno retangular de 10 m por 5 m?',
        hint: 'A cerca segue o contorno: 10 + 5 + 10 + 5.',
        visual: { kind: 'contorno', largura: 10, altura: 5 },
        options: ['30 m', '50 m', '15 m', '20 m'],
        answerIndex: 0,
      },
      {
        id: 'gm2-05',
        bloom: 'analisar',
        prompt: 'Um triangulo tem lados 5, 6 e 7. Qual o perimetro?',
        hint: 'Perimetro e a soma de todos os lados, mesmo quando sao diferentes.',
        options: ['18', '17', '35', '210'],
        answerIndex: 0,
      },
      {
        id: 'gm2-06',
        bloom: 'avaliar',
        prompt: 'Duas figuras tem o mesmo perimetro. Elas tem sempre a mesma area?',
        hint: 'Um retangulo 1x5 e um quadrado 3x3 tem perimetro 12; compare as areas.',
        options: ['Nao, a area pode ser diferente', 'Sim, sempre', 'Sim, se forem retangulos', 'Nunca'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-3',
    title: 'Area de figuras planas',
    curriculum: 'base do 5o e 6o ano — BNCC',
    years: [5, 6],
    exercises: [
      {
        id: 'gm3-01',
        bloom: 'entender',
        prompt: 'Quantos quadradinhos cobrem esta figura?',
        hint: 'Conte uma fileira e repita para as outras — e a mesma ideia da multiplicacao.',
        visual: { kind: 'grade-area', rows: 3, cols: 5 },
        options: ['15', '8', '16', '12'],
        answerIndex: 0,
      },
      {
        id: 'gm3-02',
        bloom: 'aplicar',
        prompt: 'Qual a area de um retangulo de 8 por 4?',
        hint: 'Area do retangulo e base vezes altura.',
        visual: { kind: 'grade-area', rows: 4, cols: 8 },
        options: ['32', '24', '12', '16'],
        answerIndex: 0,
      },
      {
        id: 'gm3-03',
        bloom: 'aplicar',
        prompt: 'Qual a area de um quadrado de lado 6?',
        hint: 'No quadrado, base e altura sao iguais: 6 vezes 6.',
        options: ['36', '24', '12', '18'],
        answerIndex: 0,
      },
      {
        id: 'gm3-04',
        bloom: 'aplicar',
        prompt: 'Um triangulo tem base 10 e altura 6. Qual a area?',
        hint: 'O triangulo e metade do retangulo de mesma base e altura: 10 x 6 dividido por 2.',
        options: ['30', '60', '16', '15'],
        answerIndex: 0,
      },
      {
        id: 'gm3-05',
        bloom: 'analisar',
        prompt: 'A area de um circulo se calcula por qual expressao?',
        hint: 'E onde o Pizinho entra: o numero Pi multiplicando o raio ao quadrado.',
        options: ['Pi x raio x raio', '2 x Pi x raio', 'Pi x diametro', 'raio x raio'],
        answerIndex: 0,
      },
      {
        id: 'gm3-06',
        bloom: 'avaliar',
        prompt: 'Uma sala de 4 m por 3 m recebera piso. Quantos metros quadrados comprar?',
        hint: 'Piso cobre o chao inteiro, ou seja, a area: 4 x 3.',
        visual: { kind: 'grade-area', rows: 3, cols: 4 },
        options: ['12 m2', '14 m2', '7 m2', '24 m2'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-4',
    title: 'Volume de solidos simples',
    curriculum: 'base do 6o e 7o ano — BNCC',
    years: [6, 7],
    exercises: [
      {
        id: 'gm4-01',
        bloom: 'entender',
        prompt: 'Quantos cubinhos formam este bloco de 3 por 2 por 2?',
        hint: 'Conte uma camada (3 x 2 = 6) e veja quantas camadas ha.',
        visual: { kind: 'blocos', x: 3, y: 2, z: 2 },
        options: ['12', '7', '10', '18'],
        answerIndex: 0,
      },
      {
        id: 'gm4-02',
        bloom: 'aplicar',
        prompt: 'Qual o volume de um bloco de 5 x 3 x 2?',
        hint: 'Volume do bloco retangular e comprimento x largura x altura.',
        visual: { kind: 'blocos', x: 5, y: 3, z: 2 },
        options: ['30', '10', '16', '60'],
        answerIndex: 0,
      },
      {
        id: 'gm4-03',
        bloom: 'aplicar',
        prompt: 'Um cubo tem aresta 4. Qual o volume?',
        hint: 'No cubo as tres medidas sao iguais: 4 x 4 x 4.',
        visual: { kind: 'blocos', x: 4, y: 4, z: 4 },
        options: ['64', '16', '12', '48'],
        answerIndex: 0,
      },
      {
        id: 'gm4-05',
        bloom: 'aplicar',
        prompt: 'Quantos litros cabem num recipiente de 1000 cm3?',
        hint: 'Mil centimetros cubicos equivalem a 1 litro.',
        options: ['1 litro', '10 litros', '100 litros', '0,1 litro'],
        answerIndex: 0,
      },
      {
        id: 'gm4-04',
        bloom: 'analisar',
        prompt: 'Uma caixa de 2 x 2 x 2 tem o dobro do volume de uma de 1 x 1 x 1?',
        hint: 'Calcule os dois volumes: 8 e 1. Dobrar cada aresta multiplica o volume por 8.',
        options: ['Nao, tem 8 vezes o volume', 'Sim, o dobro', 'Nao, tem 4 vezes', 'Tem o mesmo volume'],
        answerIndex: 0,
      },
      {
        id: 'gm4-06',
        bloom: 'avaliar',
        prompt: 'Qual unidade faz mais sentido para o volume de uma piscina?',
        hint: 'Pense no tamanho: mililitro seria um numero gigante.',
        options: ['Metro cubico', 'Mililitro', 'Centimetro', 'Grama'],
        answerIndex: 0,
      },
    ],
  },
  {
    id: 'etapa-5',
    title: 'Escala e conversao em contextos praticos',
    curriculum: 'base do 7o e 8o ano — BNCC',
    years: [7, 8],
    exercises: [
      {
        id: 'gm5-01',
        bloom: 'entender',
        prompt: 'Numa escala 1:100, 1 cm no desenho representa quanto no real?',
        hint: 'A escala diz: cada 1 do desenho vale 100 do real.',
        options: ['100 cm, ou 1 metro', '1 cm', '10 cm', '1000 cm'],
        answerIndex: 0,
      },
      {
        id: 'gm5-02',
        bloom: 'aplicar',
        prompt: 'Numa maquete 1:50, uma parede de 6 cm representa quantos metros?',
        hint: '6 x 50 da 300 cm. Agora converta para metros.',
        options: ['3 metros', '30 metros', '0,3 metro', '300 metros'],
        answerIndex: 0,
      },
      {
        id: 'gm5-03',
        bloom: 'aplicar',
        prompt: 'Um mapa 1:1000 mostra 4 cm entre duas ruas. Qual a distancia real?',
        hint: '4 x 1000 da 4000 cm.',
        options: ['40 metros', '4 metros', '400 metros', '4 quilometros'],
        answerIndex: 0,
      },
      {
        id: 'gm5-04',
        bloom: 'analisar',
        prompt: 'Quantos metros quadrados tem um terreno de 2 km por 1 km?',
        hint: 'Converta antes de multiplicar: 2 km sao 2000 m e 1 km sao 1000 m.',
        options: ['2000000 m2', '2 m2', '2000 m2', '200000 m2'],
        answerIndex: 0,
      },
      {
        id: 'gm5-05',
        bloom: 'avaliar',
        prompt: 'Uma receita para 4 pessoas usa 200 g de farinha. Para 6 pessoas?',
        hint: 'Ache quanto vai por pessoa (200 dividido por 4) e multiplique por 6.',
        options: ['300 g', '250 g', '400 g', '600 g'],
        answerIndex: 0,
      },
      {
        id: 'gm5-06',
        bloom: 'avaliar',
        prompt: 'Uma planta de casa esta em 1:50. Um comodo real de 4 m aparece com quantos cm?',
        hint: 'Caminho inverso: 4 m sao 400 cm; divida por 50.',
        options: ['8 cm', '20 cm', '2 cm', '80 cm'],
        answerIndex: 0,
      },
    ],
  },
]
